name: proyecto_restaurante
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets: 
  - assets/logo.png
  - assets/mapa.png
  - assets/menu.jpg
  - assets/sigin.png
  - assets/signup.png
  - assets/mijoburger.png
  - assets/papas.png
  - assets/chorizo.png
  - assets/nuggets.png
  - assets/pollo.png
  - assets/pizza.png
  - assets/hotdog.png
  - assets/taco.png
  - assets/sushi.png
  - assets/bebida.png
  - assets/booking.png
  - assets/pago.png